name: CI-CD Pipeline

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  tests:
    name: Test runner
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Set up JDK@21
        uses: actions/setup-java@v4.7.0
        with:
          distribution: 'adopt'
          java-version: '21'
      - name: Run application tests
        run: mvn test
  build:
    name: Build runner
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Set up JDK@21
        uses: actions/setup-java@v4.7.0
        with:
          distribution: 'adopt'
          java-version: '21'
      - name: Build with Maven
        run: mvn package -Dmaven.test.skip=true --file pom.xml
  deploy:
    name: Deploy runner
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Set up JDK@21
        uses: actions/setup-java@v4.7.0
        with:
          distribution: 'adopt'
          java-version: '21'
      - name: Run with Maven
        run: mvn spring-boot:run
