name: CI-CD Pipeline

on:
  push:
    branches:
      - camunda-develop
  workflow_dispatch:

jobs:
  tests:
    name: Test runner
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Set up JDK@21
        uses: actions/setup-java@v4.7.0
        with:
          distribution: 'adopt'
          java-version: '21'
      - name: Run application tests
        run: mvn test
