name: CI Pipeline

on:
  push:
    branches:
      - 'develop'
  workflow_dispatch:

jobs:
  tests:
    name: Tests runner
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Set up JDK@21
        uses: actions/setup-java@v4.7.0
        with:
          java-version: '21'
          distribution: 'adopt'
      - name: Run application tests
        run: mvn test